title: Place In Time
author: leopold chen
email: placeintime.qh@gmail.com
description: > 
  Dream it, believe it, build it.

# social links
github_username:  leopoldchen

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman

plugins:
  - jekyll-sitemap
